//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqRaporlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolge
    {
        public Bolge()
        {
            this.Bolgelers = new HashSet<Bolgeler>();
        }
    
        public int BolgeID { get; set; }
        public string BolgeTanimi { get; set; }
    
        public virtual ICollection<Bolgeler> Bolgelers { get; set; }
    }
}
