//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqRaporlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public Kategoriler()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int KategoriID { get; set; }
        public string KategoriAdi { get; set; }
        public string Tanimi { get; set; }
        public byte[] Resim { get; set; }
    
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
